with source as (

    select *
    from GEIP_PROD.LANDING.CUSTOMERS

),

deduplicated as (

    select *
    from source
    qualify row_number() over (
        partition by customer_sk
        order by updated_at desc, load_date desc
    ) = 1

)

select
    count(*) as nb_lignes,
    count(distinct customer_sk) as nb_customer_sk_uniques
from deduplicated;


SHOW VIEWS LIKE 'STG_LANDING_CUSTOMERS' IN SCHEMA GEIP_PROD.BRONZE;


SELECT GET_DDL(
    'VIEW',
    'GEIP_PROD.BRONZE.STG_LANDING_CUSTOMERS'
);



SELECT
    COUNT(*) AS nb_lignes,
    COUNT(DISTINCT customer_sk) AS nb_customer_sk_uniques
FROM GEIP_PROD.BRONZE.STG_LANDING_CUSTOMERS;


SELECT GET_DDL(
    'VIEW',
    'GEIP_PROD.BRONZE.STG_LANDING_CUSTOMERS'
);



DESC TABLE GEIP_PROD.LANDING.CONTRACTS;


select * from GEIP_PROD.LANDING.CONTRACTS;

USE DATABASE GEIP_PROD;
USE SCHEMA LANDING;
SELECT
    COUNT(*) AS nb_lignes,
    COUNT(DISTINCT contract_id) AS nb_contracts_uniques,
    COUNT(DISTINCT customer_id) AS nb_clients
FROM LANDING.CONTRACTS;

SELECT c.customer_id
FROM LANDING.CUSTOMERS c
LEFT JOIN LANDING.CONTRACTS ct
    ON c.customer_id = ct.customer_id
WHERE ct.customer_id IS NULL;


SELECT COUNT(*) AS nb_clients_sans_contrat
FROM LANDING.CUSTOMERS c
LEFT JOIN LANDING.CONTRACTS ct
    ON c.customer_id = ct.customer_id
WHERE ct.customer_id IS NULL;


SELECT CUSTOMER_ID
FROM LANDING.CUSTOMERS
LIMIT 10;


SELECT CUSTOMER_ID
FROM LANDING.CONTRACTS
LIMIT 10;



TRUNCATE TABLE LANDING.CUSTOMERS;
TRUNCATE TABLE LANDING.CONTRACTS;
TRUNCATE TABLE LANDING.METERS;
TRUNCATE TABLE LANDING.ENERGY_CONSUMPTION;
TRUNCATE TABLE LANDING.INVOICES;
TRUNCATE TABLE LANDING.PAYMENTS;
TRUNCATE TABLE LANDING.CUSTOMER_SERVICE;
TRUNCATE TABLE LANDING.OUTAGES;
TRUNCATE TABLE LANDING.MAINTENANCE;



SELECT 'CUSTOMERS' AS TABLE_NAME, COUNT(*) FROM LANDING.CUSTOMERS
UNION ALL
SELECT 'CONTRACTS', COUNT(*) FROM LANDING.CONTRACTS
UNION ALL
SELECT 'METERS', COUNT(*) FROM LANDING.METERS
UNION ALL
SELECT 'ENERGY_CONSUMPTION', COUNT(*) FROM LANDING.ENERGY_CONSUMPTION
UNION ALL
SELECT 'INVOICES', COUNT(*) FROM LANDING.INVOICES
UNION ALL
SELECT 'PAYMENTS', COUNT(*) FROM LANDING.PAYMENTS
UNION ALL
SELECT 'CUSTOMER_SERVICE', COUNT(*) FROM LANDING.CUSTOMER_SERVICE
UNION ALL
SELECT 'OUTAGES', COUNT(*) FROM LANDING.OUTAGES
UNION ALL
SELECT 'MAINTENANCE', COUNT(*) FROM LANDING.MAINTENANCE;




SELECT COUNT(*) AS NB_CONTRACTS_SANS_CLIENT
FROM LANDING.CONTRACTS c
LEFT JOIN LANDING.CUSTOMERS cu
ON c.CUSTOMER_ID = cu.CUSTOMER_ID
WHERE cu.CUSTOMER_ID IS NULL;


SELECT COUNT(*) AS NB_METERS_SANS_CONTRAT
FROM LANDING.METERS m
LEFT JOIN LANDING.CONTRACTS c
ON m.CONTRACT_ID = c.CONTRACT_ID
WHERE c.CONTRACT_ID IS NULL;


SELECT COUNT(*) AS NB_CONSO_SANS_METER
FROM LANDING.ENERGY_CONSUMPTION ec
LEFT JOIN LANDING.METERS m
ON ec.METER_ID = m.METER_ID
WHERE m.METER_ID IS NULL;

SELECT COUNT(*) AS NB_INVOICES_SANS_CONTRAT
FROM LANDING.INVOICES i
LEFT JOIN LANDING.CONTRACTS c
ON i.CONTRACT_ID = c.CONTRACT_ID
WHERE c.CONTRACT_ID IS NULL;


SELECT COUNT(*) AS NB_PAYMENTS_SANS_INVOICE
FROM LANDING.PAYMENTS p
LEFT JOIN LANDING.INVOICES i
ON p.INVOICE_ID = i.INVOICE_ID
WHERE i.INVOICE_ID IS NULL;


SELECT COUNT(*) AS NB_TICKETS_SANS_CLIENT
FROM LANDING.CUSTOMER_SERVICE cs
LEFT JOIN LANDING.CUSTOMERS cu
ON cs.CUSTOMER_ID = cu.CUSTOMER_ID
WHERE cu.CUSTOMER_ID IS NULL;


select * from contracts limit 5;

SELECT *
FROM LANDING.CUSTOMERS
LIMIT 1;


SELECT CONTRACT_ID
FROM LANDING.METERS
LIMIT 10;


TRUNCATE TABLE LANDING.CONTRACTS;

TRUNCATE TABLE LANDING.METERS;
TRUNCATE TABLE LANDING.CUSTOMER_SERVICE;



SELECT COUNT(*) AS NB_TICKETS_SANS_CLIENT
FROM LANDING.CUSTOMER_SERVICE cs
LEFT JOIN LANDING.CUSTOMERS cu
ON cs.CUSTOMER_ID = cu.CUSTOMER_ID





WHERE cu.CUSTOMER_ID IS NULL;


SELECT COUNT(*) AS NB_CONTRACTS_SANS_CLIENT
FROM LANDING.CONTRACTS c
LEFT JOIN LANDING.CUSTOMERS cu
ON c.CUSTOMER_ID = cu.CUSTOMER_ID
WHERE cu.CUSTOMER_ID IS NULL;


SELECT COUNT(*) AS NB_METERS_SANS_CONTRAT
FROM LANDING.METERS m
LEFT JOIN LANDING.CONTRACTS c
ON m.CONTRACT_ID = c.CONTRACT_ID
WHERE c.CONTRACT_ID IS NULL;


SELECT
    COUNT(*) AS NB_LIGNES,
    COUNT(DISTINCT CONTRACT_ID) AS NB_CONTRACT_ID,
    COUNT(DISTINCT CONTRACT_SK) AS NB_CONTRACT_SK
FROM LANDING.CONTRACTS;









SELECT COUNT(*) FROM BRONZE.STG_LANDING_CONTRACTS;


SELECT
    CONTRACT_TYPE,
    COUNT(*) AS NB
FROM BRONZE.STG_LANDING_CONTRACTS
GROUP BY CONTRACT_TYPE
ORDER BY NB DESC;




SELECT
    COUNT(*) AS NB_LIGNES,
    COUNT(DISTINCT METER_ID) AS NB_METER_ID,
    COUNT(DISTINCT CONTRACT_ID) AS NB_CONTRACT_ID
FROM LANDING.METERS;


SELECT
    METER_STATUS,
    COUNT(*) AS NB
FROM LANDING.METERS
GROUP BY METER_STATUS
ORDER BY NB DESC;


SELECT
    METER_TYPE,
    COUNT(*) AS NB
FROM LANDING.METERS
GROUP BY METER_TYPE
ORDER BY NB DESC;


DESC TABLE GEIP_PROD.LANDING.METERS;


SELECT
    COUNT(*) AS NB_LIGNES,
    COUNT(DISTINCT CONSUMPTION_SK) AS NB_CONSUMPTION_SK,
    COUNT(DISTINCT METER_ID) AS NB_METER_ID
FROM LANDING.ENERGY_CONSUMPTION;


DESC TABLE GEIP_PROD.LANDING.ENERGY_CONSUMPTION;

SELECT *
FROM LANDING.ENERGY_CONSUMPTION
LIMIT 5;


SELECT
    COUNT(*) AS NB_LIGNES,

    COUNT(DISTINCT
        CONCAT(
            TRIM(METER_ID),
            '|',
            TO_VARCHAR(READING_DATETIME)
        )
    ) AS NB_METER_DATETIME

FROM LANDING.ENERGY_CONSUMPTION;



SELECT
    SEASON,
    COUNT(*) AS NB
FROM LANDING.ENERGY_CONSUMPTION
GROUP BY SEASON
ORDER BY NB DESC;


SELECT
    QUALITY_FLAG,
    COUNT(*) AS NB
FROM LANDING.ENERGY_CONSUMPTION
GROUP BY QUALITY_FLAG
ORDER BY NB DESC;



DESC TABLE GEIP_PROD.LANDING.INVOICES;


SELECT
    COUNT(*) AS NB_LIGNES,
    COUNT(DISTINCT INVOICE_SK) AS NB_INVOICE_SK,
    COUNT(DISTINCT INVOICE_ID) AS NB_INVOICE_ID
FROM LANDING.INVOICES;


SELECT
    INVOICE_STATUS,
    COUNT(*) AS NB
FROM LANDING.INVOICES
GROUP BY INVOICE_STATUS
ORDER BY NB DESC;

SELECT *
FROM LANDING.INVOICES
LIMIT 5;


SELECT
    INVOICE_ID,
    COUNT(*) AS nb
FROM LANDING.INVOICES
GROUP BY INVOICE_ID
HAVING COUNT(*) >1;

SELECT
    MIN(total_amount) AS min_total,
    MAX(total_amount) AS max_total
FROM LANDING.INVOICES;

SELECT
    MIN(invoice_date) AS premiere_facture,
    MAX(invoice_date) AS derniere_facture,

    MIN(due_date) AS premiere_echeance,
    MAX(due_date) AS derniere_echeance
FROM LANDING.INVOICES;


SELECT
    COUNT(*) AS nb_factures,

    COUNT(payment_date) AS nb_factures_payees
FROM LANDING.INVOICES;


DESC TABLE GEIP_PROD.LANDING.PAYMENTS;



SELECT
    COUNT(*) AS NB_LIGNES,
    COUNT(DISTINCT PAYMENT_SK) AS NB_PAYMENT_SK,
    COUNT(DISTINCT PAYMENT_ID) AS NB_PAYMENT_ID
FROM LANDING.PAYMENTS;


SELECT
    PAYMENT_STATUS,
    COUNT(*) AS NB
FROM LANDING.PAYMENTS
GROUP BY PAYMENT_STATUS
ORDER BY NB DESC;

SELECT
    PAYMENT_METHOD,
    COUNT(*) AS NB
FROM LANDING.PAYMENTS
GROUP BY PAYMENT_METHOD
ORDER BY NB DESC;


SELECT
    MIN(AMOUNT_PAID) AS MIN_PAYMENT,
    MAX(AMOUNT_PAID) AS MAX_PAYMENT
FROM LANDING.PAYMENTS;


SELECT
  *
FROM LANDING.PAYMENTS limit 5;



DESC TABLE GEIP_PROD.LANDING.CUSTOMER_SERVICE;

SELECT
    COUNT(*) AS NB_LIGNES,
    COUNT(DISTINCT TICKET_SK) AS NB_TICKET_SK,
    COUNT(DISTINCT TICKET_ID) AS NB_TICKET_ID
FROM LANDING.CUSTOMER_SERVICE;


SELECT
    STATUS,
    COUNT(*) AS NB
FROM LANDING.CUSTOMER_SERVICE
GROUP BY STATUS
ORDER BY NB DESC;


SELECT
    PRIORITY,
    COUNT(*) AS NB
FROM LANDING.CUSTOMER_SERVICE
GROUP BY PRIORITY
ORDER BY NB DESC;


SELECT
    TICKET_TYPE,
    COUNT(*) AS NB
FROM LANDING.CUSTOMER_SERVICE
GROUP BY TICKET_TYPE
ORDER BY NB DESC;

SELECT *
FROM LANDING.CUSTOMER_SERVICE
LIMIT 5;





DESC TABLE GEIP_PROD.LANDING.OUTAGES;

SELECT
    COUNT(*) AS NB_LIGNES,
    COUNT(DISTINCT OUTAGE_SK) AS NB_OUTAGE_SK,
    COUNT(DISTINCT OUTAGE_ID) AS NB_OUTAGE_ID
FROM LANDING.OUTAGES;

SELECT
    STATUS,
    COUNT(*) AS NB
FROM LANDING.OUTAGES
GROUP BY STATUS
ORDER BY NB DESC;


SELECT
    CAUSE,
    COUNT(*) AS NB
FROM LANDING.OUTAGES
GROUP BY CAUSE
ORDER BY NB DESC;

SELECT
    SEVERITY,
    COUNT(*) AS NB
FROM LANDING.OUTAGES
GROUP BY SEVERITY
ORDER BY NB DESC;


SELECT
    MIN(DURATION_MINUTES) AS MIN_DURATION,
    MAX(DURATION_MINUTES) AS MAX_DURATION
FROM LANDING.OUTAGES;



SELECT *
FROM LANDING.OUTAGES
LIMIT 5;



DESC TABLE GEIP_PROD.LANDING.MAINTENANCE;


SELECT
    COUNT(*) AS NB_LIGNES,
    COUNT(DISTINCT MAINTENANCE_SK) AS NB_MAINTENANCE_SK,
    COUNT(DISTINCT MAINTENANCE_ID) AS NB_MAINTENANCE_ID
FROM LANDING.MAINTENANCE;

SELECT
    MAINTENANCE_TYPE,
    COUNT(*) AS NB
FROM LANDING.MAINTENANCE
GROUP BY MAINTENANCE_TYPE
ORDER BY NB DESC;

SELECT
    STATUS,
    COUNT(*) AS NB
FROM LANDING.MAINTENANCE
GROUP BY STATUS
ORDER BY NB DESC;


SELECT
    PRIORITY,
    COUNT(*) AS NB
FROM LANDING.MAINTENANCE
GROUP BY PRIORITY
ORDER BY NB DESC;


SELECT
    MIN(DURATION_HOURS) AS MIN_DURATION,
    MAX(DURATION_HOURS) AS MAX_DURATION
FROM LANDING.MAINTENANCE;

SELECT *
FROM LANDING.MAINTENANCE
LIMIT 5;



SELECT *
FROM BRONZE.INT_CUSTOMER_CONTRACTS
LIMIT 10;

SELECT COUNT(*)
FROM BRONZE.INT_CUSTOMER_CONTRACTS;


SELECT
    COUNT(*) AS NB_LIGNES,
    COUNT(DISTINCT CUSTOMER_ID) AS NB_CUSTOMERS,
    COUNT(DISTINCT CONTRACT_ID) AS NB_CONTRACTS
FROM BRONZE.INT_CUSTOMER_CONTRACTS;


SELECT
    COUNT(*) AS NB_CLIENTS_SANS_CONTRAT
FROM BRONZE.INT_CUSTOMER_CONTRACTS
WHERE CONTRACT_ID IS NULL;


USE SCHEMA SILVER;

SHOW VIEWS;

SELECT *
FROM INT_CUSTOMER_CONTRACTS
LIMIT 10;

USE SCHEMA BRONZE;
select * from stg_landing_meters limit 1;


SELECT
    COUNT(*) AS NB_LIGNES,
    COUNT(DISTINCT CONTRACT_ID) AS NB_CONTRACTS,
    COUNT(DISTINCT METER_ID) AS NB_METERS
FROM SILVER.INT_CONTRACT_METERS;


SELECT *
FROM SILVER.INT_CONTRACT_METERS
LIMIT 10;

SELECT
    COUNT(*) AS NB_CONTRATS_SANS_COMPTEUR
FROM SILVER.INT_CONTRACT_METERS
WHERE METER_ID IS NULL;


SELECT *
FROM BRONZE.STG_LANDING_ENERGY_CONSUMPTION
LIMIT 1;

SELECT *
FROM BRONZE.STG_LANDING_METERS
LIMIT 1;


SELECT
    COUNT(*) AS NB_LIGNES,
    COUNT(DISTINCT CONSUMPTION_SK) AS NB_CONSUMPTIONS,
    COUNT(DISTINCT METER_ID) AS NB_METERS
FROM SILVER.INT_METER_CONSUMPTION;

SELECT *
FROM SILVER.INT_METER_CONSUMPTION
LIMIT 10;


SELECT
    COUNT(*) AS NB_CONSOMMATIONS_SANS_COMPTEUR
FROM SILVER.INT_METER_CONSUMPTION
WHERE METER_SK IS NULL;


SELECT *
FROM BRONZE.STG_LANDING_INVOICES
LIMIT 1;

SELECT *
FROM BRONZE.STG_LANDING_PAYMENTS
LIMIT 1;


SELECT
    COUNT(*) AS NB_LIGNES,
    COUNT(DISTINCT INVOICE_ID) AS NB_FACTURES,
    COUNT(DISTINCT PAYMENT_ID) AS NB_PAIEMENTS
FROM SILVER.INT_INVOICE_PAYMENTS;


SELECT
    COUNT(*) AS NB_FACTURES_SANS_PAIEMENT
FROM SILVER.INT_INVOICE_PAYMENTS
WHERE PAYMENT_ID IS NULL;


SELECT *
FROM SILVER.INT_INVOICE_PAYMENTS
LIMIT 10;

SELECT *
FROM BRONZE.STG_LANDING_CUSTOMER_SERVICE
LIMIT 1;


SELECT
    COUNT(*) AS NB_LIGNES,
    COUNT(DISTINCT TICKET_ID) AS NB_TICKETS,
    COUNT(DISTINCT CUSTOMER_ID) AS NB_CLIENTS
FROM SILVER.INT_CUSTOMER_SERVICE;


SELECT
    COUNT(*) AS NB_TICKETS_SANS_CONTRAT
FROM SILVER.INT_CUSTOMER_SERVICE
WHERE CONTRACT_SK IS NULL;


SELECT *
FROM SILVER.INT_CUSTOMER_SERVICE
LIMIT 10;


SELECT *
FROM BRONZE.STG_LANDING_OUTAGES
LIMIT 1;

SELECT *
FROM BRONZE.STG_LANDING_CONTRACTS
LIMIT 1;

SELECT *
FROM BRONZE.STG_LANDING_METERS
LIMIT 1;

SELECT
    COUNT(*) AS NB_DIFFERENCES
FROM BRONZE.STG_LANDING_OUTAGES o
JOIN BRONZE.STG_LANDING_METERS m
    ON o.METER_ID = m.METER_ID
WHERE o.CONTRACT_ID <> m.CONTRACT_ID;



SELECT
    COUNT(*) AS NB_LIGNES,
    COUNT(DISTINCT OUTAGE_ID) AS NB_PANNES,
    COUNT(DISTINCT CONTRACT_ID) AS NB_CONTRATS,
    COUNT(DISTINCT METER_ID) AS NB_COMPTEURS
FROM SILVER.INT_OUTAGES;



SELECT
    COUNT(*) AS NB_PANNES_SANS_CONTRAT
FROM SILVER.INT_OUTAGES
WHERE CONTRACT_SK IS NULL;


SELECT
    COUNT(*) AS NB_PANNES_SANS_COMPTEUR
FROM SILVER.INT_OUTAGES
WHERE METER_SK IS NULL;

SELECT *
FROM SILVER.INT_OUTAGES
LIMIT 10;

SELECT
    COUNT(*) AS NB_DIFFERENCES
FROM BRONZE.STG_LANDING_MAINTENANCE mt
JOIN BRONZE.STG_LANDING_METERS m
    ON mt.METER_ID = m.METER_ID
WHERE mt.CONTRACT_ID <> m.CONTRACT_ID;


SELECT *
FROM BRONZE.STG_LANDING_MAINTENANCE
LIMIT 1;


SELECT
    COUNT(*) AS NB_LIGNES,
    COUNT(DISTINCT MAINTENANCE_ID) AS NB_MAINTENANCES,
    COUNT(DISTINCT CONTRACT_ID) AS NB_CONTRATS,
    COUNT(DISTINCT METER_ID) AS NB_COMPTEURS
FROM SILVER.INT_MAINTENANCE;


SELECT
    COUNT(*) AS NB_MAINTENANCES_SANS_CONTRAT
FROM SILVER.INT_MAINTENANCE
WHERE CONTRACT_SK IS NULL;

SELECT
    COUNT(*) AS NB_MAINTENANCES_SANS_COMPTEUR
FROM SILVER.INT_MAINTENANCE
WHERE METER_SK IS NULL;

SELECT *
FROM SILVER.INT_MAINTENANCE
LIMIT 10;

SELECT *
FROM SILVER.INT_CUSTOMER_CONTRACTS
LIMIT 1;


SELECT *
FROM LANDING.CONTRACTS
LIMIT 1;


SHOW VIEWS LIKE 'INT_CUSTOMER_CONTRACTS' IN SCHEMA SILVER;


SELECT *
FROM SILVER.INT_CUSTOMER_CONTRACTS
LIMIT 1;


SELECT
    CUSTOMER_ID,
    COUNT(*) AS NB

FROM GOLD.DIM_CUSTOMERS

GROUP BY CUSTOMER_ID

HAVING COUNT(*) > 1;


SELECT

    COUNT(DISTINCT CUSTOMER_ID) AS NB_CUSTOMERS

FROM SILVER.INT_CUSTOMER_CONTRACTS;


SELECT

    COUNT(*) AS NB_CUSTOMERS

FROM GOLD.DIM_CUSTOMERS;

SELECT *

FROM GOLD.DIM_CUSTOMERS

LIMIT 10;


SELECT *
from SILVER.INT_CUSTOMER_CONTRACTS

WHERE CONTRACT_ID IS NULL;

select * from gold.dim_date limit 10;


SELECT *

FROM GOLD.FACT_ENERGY_CONSUMPTION

LIMIT 10;


SELECT COUNT(*)

FROM GOLD.FACT_ENERGY_CONSUMPTION;


select * from stg_landing_invoices limit 1;

SELECT *

FROM GOLD.FACT_INVOICES

LIMIT 10;

SELECT COUNT(*)

FROM GOLD.FACT_INVOICES ;


SELECT
    INVOICE_ID,
    COUNT(*)
FROM SILVER.INT_INVOICE_PAYMENTS
GROUP BY INVOICE_ID
HAVING COUNT(*) > 1 limit 10;

SELECT
    INVOICE_SK,
    COUNT(*) AS NB_OCCURRENCES
FROM GOLD.FACT_INVOICES
GROUP BY INVOICE_SK
HAVING COUNT(*) > 1
ORDER BY NB_OCCURRENCES DESC;

SELECT
    COUNT(*) AS NB_FACTURES_EN_DOUBLON
FROM (

    SELECT
        INVOICE_SK
    FROM GOLD.FACT_INVOICES
    GROUP BY INVOICE_SK
    HAVING COUNT(*) > 1

);

SELECT COUNT(*) AS NB_LIGNES
FROM GOLD.FACT_INVOICES;

SELECT COUNT(DISTINCT INVOICE_SK) AS NB_FACTURES
FROM GOLD.FACT_INVOICES;


select * from stg_landing_invoices limit 1;


select * from stg_landing_customers limit 1;


SELECT *

FROM SNAPSHOTS.SNAPSHOT_CUSTOMERS


LIMIT 10;


SELECT
    CUSTOMER_ID,
    CUSTOMER_SEGMENT,
    STATUS,
    UPDATED_AT
FROM STG_LANDING_CUSTOMERS
WHERE CUSTOMER_ID = 'CUST0485321';
LIMIT 1;


UPDATE LANDING.CUSTOMERS
SET

    CUSTOMER_SEGMENT = 'VIP',

    STATUS = 'ACTIVE',

    UPDATED_AT = CURRENT_TIMESTAMP()

WHERE CUSTOMER_ID = 'CUST0485321';


SELECT
    CUSTOMER_ID,
    CUSTOMER_SEGMENT,
    STATUS,
    UPDATED_AT,
    DBT_VALID_FROM,
    DBT_VALID_TO
FROM SNAPSHOTS.SNAPSHOT_CUSTOMERS
WHERE CUSTOMER_ID = 'CUST0485321'
ORDER BY DBT_VALID_FROM;


UPDATE LANDING.CUSTOMERS

SET

    CUSTOMER_SEGMENT = 'VIP',
    STATUS = 'ACTIVE'

WHERE CUSTOMER_ID = 'CUST0022353';



SELECT

    CUSTOMER_ID,
    CUSTOMER_SEGMENT,
    STATUS,
    UPDATED_AT,
    DBT_VALID_FROM,
    DBT_VALID_TO

FROM SNAPSHOTS.SNAPSHOT_CUSTOMERS_CHECK

WHERE CUSTOMER_ID='CUST0022353'

ORDER BY DBT_VALID_FROM;


UPDATE GOLD.FACT_ENERGY_CONSUMPTION
SET ENERGY_CONSUMED_KWH = -100
WHERE CONSUMPTION_SK = 1;


SELECT *

FROM GOLD.FACT_ENERGY_CONSUMPTION

WHERE CONSUMPTION_SK = 1;

UPDATE GOLD.FACT_ENERGY_CONSUMPTION
SET ENERGY_CONSUMED_KWH = 520
WHERE CONSUMPTION_SK = 1;


SELECT *
FROM GOLD.FACT_PAYMENTS
LIMIT 1;


SELECT *
FROM GOLD.FACT_PAYMENTS
LIMIT 1;

SELECT *
FROM STG_LANDING_PAYMENTS
LIMIT 1;


DESC TABLE GOLD.FACT_INVOICES;


SELECT *
FROM GOLD.DIM_METERS
LIMIT 5;


DESC TABLE GOLD.DIM_CONTRACTS;


select * from gold.dim_customers limit 1;

SELECT COUNT(*)
FROM GOLD.RPT_CUSTOMER_OVERVIEW;

SELECT *

FROM GOLD.RPT_CUSTOMER_OVERVIEW

LIMIT 20;


SELECT

    CUSTOMER_ID,

    FIRST_NAME,

    LAST_NAME,

    TOTAL_KWH

FROM GOLD.RPT_CUSTOMER_OVERVIEW

ORDER BY TOTAL_KWH DESC

LIMIT 20;


SELECT

    CUSTOMER_ID,

    FIRST_NAME,

    LAST_NAME,

    CUSTOMER_LIFETIME_VALUE

FROM GOLD.RPT_CUSTOMER_OVERVIEW

ORDER BY CUSTOMER_LIFETIME_VALUE DESC

LIMIT 20;


SELECT

    CUSTOMER_ID,

    TOTAL_BILLED,

    TOTAL_PAID,

    OUTSTANDING_BALANCE

FROM GOLD.RPT_CUSTOMER_OVERVIEW

ORDER BY OUTSTANDING_BALANCE DESC

LIMIT 20;


SELECT *

FROM GOLD.RPT_CUSTOMER_OVERVIEW

WHERE NB_CONTRACTS = 0;


SELECT

    COUNT(*)                       AS NB_CLIENTS,

    SUM(NB_CONTRACTS)              AS NB_CONTRATS,

    SUM(NB_METERS)                 AS NB_COMPTEURS,

    SUM(TOTAL_KWH)                 AS KWH_TOTAL,

    SUM(TOTAL_BILLED)              AS MONTANT_FACTURE,

    SUM(TOTAL_PAID)                AS MONTANT_PAYE,

    SUM(OUTSTANDING_BALANCE)       AS RESTE_A_PAYER

FROM GOLD.RPT_CUSTOMER_OVERVIEW;


SELECT

    CUSTOMER_ID,

    COUNT(*)

FROM GOLD.RPT_CUSTOMER_OVERVIEW

GROUP BY CUSTOMER_ID

HAVING COUNT(*) > 1;


SELECT *

FROM GOLD.RPT_ENERGY_DASHBOARD

LIMIT 20;


select * from gold.fact_payments ;

SELECT *

FROM GOLD.RPT_CONTRACT_DASHBOARD

LIMIT 20;


SELECT *
FROM silver.int_maintenance
LIMIT 5;


SELECT *

FROM GOLD.RPT_MAINTENANCE_DASHBOARD

LIMIT 20;


SELECT *
FROM silver.int_outages 
LIMIT 5;

SELECT *

FROM GOLD.FACT_INVOICES

LIMIT 20;


SELECT *
FROM landing.meters
LIMIT 1;


SELECT

CONTRACT_ID,

CONTRACT_START_DATE_SK,

CONTRACT_END_DATE_SK,

CONTRACT_CREATED_DATE_SK,

CONTRACT_UPDATED_DATE_SK

FROM GOLD.RPT_CONTRACT_DASHBOARD

LIMIT 20;


SELECT

CONTRACT_ID,

CONTRACT_START_DATE,

YEAR,

MONTH,

MONTH_NAME,

QUARTER,

SEASON,

DAY_NAME,

IS_WEEKEND

FROM GOLD.RPT_CONTRACT_DASHBOARD

LIMIT 20;


SELECT

IS_ACTIVE,

IS_SUSPENDED,

IS_TERMINATED,

COUNT(*) AS NB

FROM GOLD.RPT_CONTRACT_DASHBOARD

GROUP BY

IS_ACTIVE,

IS_SUSPENDED,

IS_TERMINATED;


SELECT *
FROM GOLD.RPT_CONTRACT_DASHBOARD;

SELECT *
FROM GOLD.RPT_CUSTOMER_OVERVIEW
LIMIT 20;

select * from gold.fact_energy_consumption limit 1;


SELECT *
FROM GOLD.FACT_PAYMENTS
LIMIT 1;


SELECT
    COUNT(*)
FROM GOLD.fact_invoices
WHERE IS_PAID = TRUE
AND PAYMENT_DATE IS NULL;

SELECT
    IS_PAID,
    PAYMENT_DATE,
    COUNT(*) AS NB
FROM GOLD.fact_invoices
GROUP BY
    IS_PAID,
    PAYMENT_DATE
ORDER BY NB DESC;


SELECT
    COUNT(*) AS NB
FROM GOLD.fact_invoices
WHERE IS_PAID = TRUE;


SELECT
    COUNT(*) AS NB
FROM BRONZE.stg_landing_invoices
WHERE IS_PAID = TRUE
  AND PAYMENT_DATE IS NULL;


SELECT
    COUNT(*) AS NB
FROM GOLD.fact_invoices
WHERE IS_PAID = TRUE
AND PAYMENT_DATE IS NULL;


SELECT
    COUNT(*)
FROM SILVER.int_invoice_payments
WHERE IS_PAID = TRUE
AND PAYMENT_DATE IS NULL;

SELECT COUNT(*)
FROM BRONZE.STG_LANDING_PAYMENTS
WHERE PAYMENT_DATE IS NULL;

SELECT
    IS_SUCCESSFUL_PAYMENT,
    COUNT(*)
FROM BRONZE.STG_LANDING_PAYMENTS
GROUP BY IS_SUCCESSFUL_PAYMENT;



SELECT
    IS_PAID,
    PAYMENT_DATE,
    PAYMENT_SK,
    PAYMENT_STATUS,
    COUNT(*) AS NB
FROM SILVER.INT_INVOICE_PAYMENTS
WHERE IS_PAID = TRUE
GROUP BY
    IS_PAID,
    PAYMENT_DATE,
    PAYMENT_SK,
    PAYMENT_STATUS
ORDER BY NB DESC;



SELECT *
FROM SILVER.INT_INVOICE_PAYMENTS
LIMIT 1;

SELECT
    INVOICE_ID,
    IS_PAID,
    PAYMENT_DATE,
    PAYMENT_SK,
    PAYMENT_STATUS,
    PAYMENT_ID,
    PAYMENT_CREATED_AT
FROM SILVER.INT_INVOICE_PAYMENTS
WHERE IS_PAID = TRUE
  AND PAYMENT_DATE IS NULL
LIMIT 20;

SELECT
    COUNT(*)
FROM BRONZE.STG_LANDING_INVOICES i
LEFT JOIN BRONZE.STG_LANDING_PAYMENTS p
       ON i.INVOICE_ID = p.INVOICE_ID
WHERE i.IS_PAID = TRUE
  AND p.PAYMENT_DATE IS NULL;

  SELECT *
FROM BRONZE.STG_LANDING_PAYMENTS
WHERE INVOICE_ID = 'INV000555241';


SELECT
    invoice_status,
    COUNT(*)
FROM BRONZE.STG_LANDING_INVOICES
WHERE payment_date IS NULL
GROUP BY invoice_status;

SELECT
    COUNT(*)
FROM BRONZE.STG_LANDING_INVOICES
WHERE invoice_status = 'PAID'
  AND payment_date IS NULL;


  SELECT
    COUNT(*) AS NB_PAID_NULL
FROM BRONZE.STG_LANDING_INVOICES
WHERE IS_PAID = TRUE
  AND PAYMENT_DATE IS NULL;
SELECT
    i.INVOICE_ID,
    i.IS_PAID,
    i.PAYMENT_DATE AS INVOICE_PAYMENT_DATE,
    p.PAYMENT_DATE AS PAYMENT_PAYMENT_DATE
FROM BRONZE.STG_LANDING_INVOICES i
LEFT JOIN BRONZE.STG_LANDING_PAYMENTS p
    ON i.INVOICE_ID = p.INVOICE_ID
WHERE i.INVOICE_ID = 'INV000555241';

SELECT
    COUNT(*) AS NB_PAID_NULL
FROM SILVER.INT_INVOICE_PAYMENTS
WHERE IS_PAID = TRUE
  AND PAYMENT_DATE IS NULL;


  SELECT
    i.INVOICE_ID,
    LENGTH(i.INVOICE_ID) AS LEN_INV,
    p.INVOICE_ID,
    LENGTH(p.INVOICE_ID) AS LEN_PAY
FROM BRONZE.STG_LANDING_INVOICES i
FULL OUTER JOIN BRONZE.STG_LANDING_PAYMENTS p
    ON i.INVOICE_ID = p.INVOICE_ID
WHERE i.INVOICE_ID = 'INV000555241'
   OR p.INVOICE_ID = 'INV000555241';

   SELECT *
FROM BRONZE.STG_LANDING_PAYMENTS
WHERE TRIM(INVOICE_ID)='INV000555241';


SELECT *
FROM LANDING.PAYMENTS
WHERE INVOICE_ID = 'INV000555241';


SELECT
    invoice_id,
    invoice_status,
    payment_date
FROM LANDING.INVOICES
WHERE invoice_id = 'INV000555241';

select * from silver.int_invoice_payments WHERE invoice_id = 'INV000555241';limit 1;

select * from landing.payments WHERE invoice_id = 'INV000555241';

select * from landing.invoices WHERE invoice_id = 'INV000555241';


SELECT
    INVOICE_ID,
    IS_PAID,
    PAYMENT_DATE,
    PAYMENT_SK,
    PAYMENT_ID,
    PAYMENT_CREATED_AT
FROM SILVER.INT_INVOICE_PAYMENTS
WHERE IS_PAID = TRUE
LIMIT 20;

SELECT
    INVOICE_ID,
    PAYMENT_DATE,
    INVOICE_STATUS
FROM BRONZE.STG_LANDING_INVOICES
WHERE INVOICE_STATUS = 'PAID' and INVOICE_ID = 'INV000555241';
LIMIT 20;

SELECT *
FROM BRONZE.STG_LANDING_PAYMENTS
WHERE INVOICE_ID = 'INV000555241';


SELECT
    invoice_sk,
    COUNT(*) nb
FROM GOLD.fact_invoices
GROUP BY invoice_sk
HAVING COUNT(*) > 1
LIMIT 20;

SELECT
    invoice_sk,
    COUNT(*) AS nb
FROM BRONZE.stg_landing_invoices
GROUP BY invoice_sk
HAVING COUNT(*) > 1;

SELECT
    invoice_sk,
    COUNT(*) AS nb
FROM SILVER.int_invoice_payments
GROUP BY invoice_sk
HAVING COUNT(*) > 1;

SELECT
    invoice_id,
    COUNT(*) AS nb
FROM BRONZE.stg_landing_payments
GROUP BY invoice_id
HAVING COUNT(*) > 1
ORDER BY nb DESC LIMIT 10;


SELECT
    invoice_sk,
    COUNT(*)
FROM BRONZE.stg_landing_invoices
GROUP BY invoice_sk
HAVING COUNT(*) > 1;

SELECT
    invoice_sk,
    COUNT(*) AS nb
FROM GOLD.fact_invoices
GROUP BY invoice_sk
HAVING COUNT(*) > 1 limit 10;

SELECT *
FROM GOLD.fact_invoices
WHERE invoice_sk = 1790;


SELECT
    contract_id,
    COUNT(*) AS nb
FROM GOLD.dim_contracts
GROUP BY contract_id
HAVING COUNT(*) > 1;


SELECT
    meter_id,
    COUNT(*) AS nb
FROM GOLD.dim_meters
GROUP BY meter_id
HAVING COUNT(*) > 1;

SELECT
    full_date,
    COUNT(*) AS nb
FROM GOLD.dim_date
GROUP BY full_date
HAVING COUNT(*) > 1;


SELECT
    invoice_sk,
    COUNT(*)
FROM GOLD.fact_invoices
GROUP BY invoice_sk
HAVING COUNT(*) > 1;


SELECT *
FROM BRONZE.stg_landing_invoices
WHERE invoice_sk = 1790;

SELECT *
FROM GOLD.fact_invoices
WHERE invoice_sk = 1790;

SELECT
    invoice_sk,
    COUNT(*) AS nb
FROM GOLD.fact_invoices
GROUP BY invoice_sk
HAVING COUNT(*) > 1;


SELECT DISTINCT CONTRACT_TYPE
FROM BRONZE.STG_LANDING_CONTRACTS;

SELECT DISTINCT ENERGY_TYPE
FROM BRONZE.STG_LANDING_CONTRACTS;

SELECT DISTINCT PAYMENT_FREQUENCY
FROM BRONZE.STG_LANDING_CONTRACTS;


select * from gold.dim_contracts limit 1;


SELECT DISTINCT PAYMENT_METHOD
FROM BRONZE.STG_LANDING_PAYMENTS
ORDER BY 1;


select distinct meter_type
from GOLD.dim_meters;


SELECT
    ENERGY_CONSUMED_KWH,
    PEAK_KWH,
    OFF_PEAK_KWH,
    PEAK_KWH + OFF_PEAK_KWH AS TOTAL,
    ENERGY_CONSUMED_KWH - (PEAK_KWH + OFF_PEAK_KWH) AS ECART
FROM GOLD.FACT_ENERGY_CONSUMPTION
WHERE ABS(
        ENERGY_CONSUMED_KWH
      - (PEAK_KWH + OFF_PEAK_KWH)
      ) > 0.01
LIMIT 20;



SELECT
    p.payment_id,
    p.invoice_sk,
    p.amount_paid,
    i.total_amount,
    p.amount_paid - i.total_amount AS ecart
FROM GOLD.fact_payments p
JOIN GOLD.fact_invoices i
    ON p.invoice_sk = i.invoice_sk
WHERE p.amount_paid > i.total_amount
LIMIT 20;

DESC TABLE BRONZE.STG_LANDING_INVOICES;

SELECT
    ENERGY_AMOUNT,
    FIXED_CHARGE,
    TAX_AMOUNT,
    TOTAL_AMOUNT
FROM landing.INVOICES
LIMIT 10;

SELECT
    TOTAL_AMOUNT
FROM landing.INVOICES
LIMIT 10;



SELECT
    p.payment_id,
    p.invoice_sk,
    p.amount_paid,
    i.total_amount
FROM GOLD.fact_payments p
JOIN GOLD.fact_invoices i
    ON p.invoice_sk = i.invoice_sk
WHERE p.payment_id = 'PAY000086154';


SELECT
    invoice_sk,
    total_amount
FROM LANDING.INVOICES
WHERE invoice_sk = 633366;

SELECT
    invoice_sk,
    total_amount
FROM BRONZE.STG_LANDING_INVOICES
WHERE invoice_sk = 633366;

SELECT
    invoice_sk,
    total_amount
FROM GOLD.FACT_INVOICES
WHERE invoice_sk = 633366;


SELECT
    invoice_sk,
    total_amount
FROM GOLD.fact_invoices
WHERE invoice_sk IN (
    633366,
    483811,
    393806,
    945515,
    205315
);


SELECT
    invoice_sk,
    total_amount
FROM LANDING.invoices
WHERE invoice_sk IN (
    633366,
    483811,
    393806,
    945515,
    205315
);


SELECT
    invoice_sk,
    total_amount
FROM BRONZE.stg_landing_invoices
WHERE invoice_sk IN (
393806,
483811,
633366,
205315,
945515
);


DESC TABLE LANDING.INVOICES;

SELECT
    invoice_sk,
    energy_amount,
    fixed_charge,
    tax_amount,
    total_amount
FROM LANDING.INVOICES
WHERE invoice_sk IN (
    633366,
    483811,
    393806,
    205315,
    945515
);

SHOW CREATE VIEW STG_LANDING_INVOICES;

SHOW CREATE VIEW GEIP_PROD.BRONZE.STG_LANDING_INVOICES;

LIST 'snow://workspace/USER$.PUBLIC."DEFAULT$"/versions/head/';

GET 'snow://workspace/USER$.PUBLIC."DEFAULT$"/versions/live/'
  'file://C:/Users/ouatt/Documents/Projet%20GEIP/geip_dbt/snowflake/';


  SELECT
    CURRENT_ORGANIZATION_NAME(),
    CURRENT_ACCOUNT(),
    CURRENT_REGION();

    SELECT CURRENT_ACCOUNT();

    SELECT CURRENT_ACCOUNT_NAME();

    SELECT CURRENT_ORGANIZATION_NAME() || '-' || CURRENT_ACCOUNT_NAME();


    SELECT CURRENT_ACCOUNT(),
       CURRENT_ACCOUNT_NAME(),
       CURRENT_ORGANIZATION_NAME(),
       CURRENT_REGION(),
       CURRENT_VERSION();


       SELECT SYSTEM$GET_LOGIN_URL();