name: 'geip_dbt'
version: '1.0.0'
config-version: 2

profile: 'geip_dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"

clean-targets:
  - "target"
  - "dbt_packages"

models:
  geip_dbt:

    +persist_docs:
      relation: true
      columns: true

    # ============================
    # STAGING
    # ============================
    staging:
      +schema: BRONZE
      +materialized: view

    # ============================
    # INTERMEDIATE
    # ============================
    intermediate:
      +schema: SILVER
      +materialized: view

    # ============================
    # MARTS
    # ============================
    marts:

      dimensions:
        +schema: GOLD
        +materialized: table

      facts:
        +schema: GOLD
        +materialized: incremental

      reporting:
        +schema: GOLD
        +materialized: view

vars:
  project_name: "GEIP"
  project_owner: "Data Engineering"