USE ROLE ACCOUNTADMIN;
USE DATABASE GEIP_PROD;
USE SCHEMA LANDING;


CREATE OR REPLACE STAGE GEIP_PROD.LANDING.GEIP_S3_STAGE
URL = 's3://geip-data-lake-ouattara/'
FILE_FORMAT = GEIP_PROD.LANDING.CSV_FORMAT
CREDENTIALS = (
    AWS_KEY_ID = '****************'
    AWS_SECRET_KEY = '************************'
);

LIST @GEIP_PROD.LANDING.GEIP_S3_STAGE;

