USE DATABASE GEIP_PROD;
USE SCHEMA LANDING;

COPY INTO CUSTOMERS
FROM @GEIP_S3_STAGE/landing/customers/
FILE_FORMAT = (FORMAT_NAME = CSV_FORMAT);

COPY INTO CONTRACTS
FROM @GEIP_S3_STAGE/landing/contracts/
FILE_FORMAT = (FORMAT_NAME = CSV_FORMAT);

COPY INTO METERS
FROM @GEIP_S3_STAGE/landing/meters/
FILE_FORMAT = (FORMAT_NAME = CSV_FORMAT);

COPY INTO ENERGY_CONSUMPTION
FROM @GEIP_S3_STAGE/landing/energy_consumption/
FILE_FORMAT = (FORMAT_NAME = CSV_FORMAT);

COPY INTO INVOICES
FROM @GEIP_S3_STAGE/landing/invoices/
FILE_FORMAT = (FORMAT_NAME = CSV_FORMAT);

COPY INTO PAYMENTS
FROM @GEIP_S3_STAGE/landing/payments/
FILE_FORMAT = (FORMAT_NAME = CSV_FORMAT);

COPY INTO CUSTOMER_SERVICE
FROM @GEIP_S3_STAGE/landing/customer_service/
FILE_FORMAT = (FORMAT_NAME = CSV_FORMAT);

COPY INTO OUTAGES
FROM @GEIP_S3_STAGE/landing/outages/
FILE_FORMAT = (FORMAT_NAME = CSV_FORMAT);

COPY INTO MAINTENANCE
FROM @GEIP_S3_STAGE/landing/maintenance/
FILE_FORMAT = (FORMAT_NAME = CSV_FORMAT);