SELECT 'CUSTOMERS' AS TABLE_NAME, COUNT(*) AS NB_ROWS
FROM GEIP_PROD.LANDING.CUSTOMERS

UNION ALL

SELECT 'CONTRACTS', COUNT(*)
FROM GEIP_PROD.LANDING.CONTRACTS

UNION ALL

SELECT 'CUSTOMER_SERVICE', COUNT(*)
FROM GEIP_PROD.LANDING.CUSTOMER_SERVICE

UNION ALL

SELECT 'ENERGY_CONSUMPTION', COUNT(*)
FROM GEIP_PROD.LANDING.ENERGY_CONSUMPTION

UNION ALL

SELECT 'INVOICES', COUNT(*)
FROM GEIP_PROD.LANDING.INVOICES

UNION ALL

SELECT 'MAINTENANCE', COUNT(*)
FROM GEIP_PROD.LANDING.MAINTENANCE

UNION ALL

SELECT 'METERS', COUNT(*)
FROM GEIP_PROD.LANDING.METERS

UNION ALL

SELECT 'OUTAGES', COUNT(*)
FROM GEIP_PROD.LANDING.OUTAGES

UNION ALL

SELECT 'PAYMENTS', COUNT(*)
FROM GEIP_PROD.LANDING.PAYMENTS;





select *
FROM GEIP_PROD.LANDING.CUSTOMERS

SELECT CURRENT_ROLE();


DESCRIBE TABLE GEIP_PROD.LANDING.CUSTOMERS;